In [2]:
import tensorflow as tf

a = tf.constant(3, dtype=tf.int32, shape=(2, 3))
print(a)
print(a.numpy())



tf.Tensor(
[[3 3 3]
 [3 3 3]], shape=(2, 3), dtype=int32)
[[3 3 3]
 [3 3 3]]


In [ ]:
import numpy as np
b=np.array([1,2,3])
c=tf.constant(b)
print(c)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
